// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/firebaseConfigLoader.ts";
import * as $$$1 from "./loaders/iconsAdminLoader.ts";
import * as $$$2 from "./loaders/logoIconsAdminLoader.ts";
import * as $$$3 from "./loaders/weatherLoader.ts";
import * as $$$$$$0 from "./sections/Container.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/ItWorks.tsx";
import * as $$$$$$3 from "./sections/LinkBar.tsx";
import * as $$$$$$4 from "./sections/LoginButton.tsx";
import * as $$$$$$5 from "./sections/Paragraph.tsx";
import * as $$$$$$6 from "./sections/SystemStatus.tsx";
import * as $$$$$$7 from "./sections/Theme/Theme.tsx";
import * as $$$$$$8 from "./sections/Weather.tsx";
import * as $$$$$$9 from "./sections/WelcomeMessage.tsx";

const manifest = {
  "loaders": {
    "site/loaders/firebaseConfigLoader.ts": $$$0,
    "site/loaders/iconsAdminLoader.ts": $$$1,
    "site/loaders/logoIconsAdminLoader.ts": $$$2,
    "site/loaders/weatherLoader.ts": $$$3,
  },
  "sections": {
    "site/sections/Container.tsx": $$$$$$0,
    "site/sections/Footer.tsx": $$$$$$1,
    "site/sections/ItWorks.tsx": $$$$$$2,
    "site/sections/LinkBar.tsx": $$$$$$3,
    "site/sections/LoginButton.tsx": $$$$$$4,
    "site/sections/Paragraph.tsx": $$$$$$5,
    "site/sections/SystemStatus.tsx": $$$$$$6,
    "site/sections/Theme/Theme.tsx": $$$$$$7,
    "site/sections/Weather.tsx": $$$$$$8,
    "site/sections/WelcomeMessage.tsx": $$$$$$9,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
